name: Deploy zh-Hans Pages

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: wiki

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: wiki/yarn.lock
      - run: yarn install --frozen-lockfile

      - name: Build
        run: yarn zh-Hans:build

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: wiki/zh-Hans/.vitepress/dist
          publish_branch: zh-hans-pages

      - name: Trigger a webhook
        uses: joelwmale/webhook-action@master
        with:
          url: ${{ secrets.WEBHOOK_URL }}
