name: Deploy zh-Hans Wiki

on:
  push:
    branches:
      - main

defaults:
  run:
    working-directory: wiki

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: yarn
          cache-dependency-path: wiki/yarn.lock
      - run: yarn install --frozen-lockfile

      - name: Build
        run: yarn zh-Hans:build

      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: zh-hans-pages
